# Generated by Django 6.0.6 on 2026-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_liveroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveroom',
            name='private_host_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='liveroom',
            name='public_code',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
