# Generated by Django 6.0.6 on 2026-06-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_liveroom_private_host_key_liveroom_public_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveroom',
            name='pinned_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='liveroom',
            name='theme',
            field=models.CharField(default='neon', max_length=32),
        ),
    ]
