# Generated by Django 5.2.15 on 2026-07-01 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_phase10_statuses_full'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatfoldermembership',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statusprivacyoverride',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='adminrole',
            name='unique_user_role',
        ),
        migrations.RemoveConstraint(
            model_name='bannedip',
            name='unique_banned_ip',
        ),
        migrations.RemoveConstraint(
            model_name='chatfolder',
            name='unique_folder_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='chatfoldermembership',
            name='unique_folder_thread',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report_per_target',
        ),
        migrations.RemoveConstraint(
            model_name='smartreplycache',
            name='unique_smart_reply_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='spamreport',
            name='unique_spam_report_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='usersession',
            name='unique_session_jti',
        ),
        migrations.AlterField(
            model_name='adminbroadcast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Per-role override permissions. Empty = use the role default.'),
        ),
        migrations.AlterField(
            model_name='backuparchive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bannedip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Call duration in seconds. 0 = never connected.'),
        ),
        migrations.AlterField(
            model_name='chatfolder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatfoldermembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='avatar',
            field=models.TextField(blank=True, help_text='Base64 data URL. Same encoding as Profile.avatar.', null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public groups are joinable via invite link without admin approval.'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pinnedmessage',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Nullable so a later "Delete for Everyone" on the original message does NOT cascade-fail with an IntegrityError. The pinned banner survives with a null FK; the FE detects the null and renders a "message removed" placeholder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_rows', to='api.message'),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_id',
            field=models.BigIntegerField(help_text='ID of the target row. Generic to support all target types in one column.'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartreplycache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spamreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusmedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusprivacyoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusreaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_kind',
            field=models.CharField(blank=True, default='', help_text='"mobile" | "tablet" | "desktop" | "bot" | ""', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userthreadsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='adminrole',
            unique_together={('user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='bannedip',
            unique_together={('ip_address',)},
        ),
        migrations.AlterUniqueTogether(
            name='chatfolder',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='chatfoldermembership',
            unique_together={('folder', 'thread')},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'target_type', 'target_id', 'reason')},
        ),
        migrations.AlterUniqueTogether(
            name='smartreplycache',
            unique_together={('thread', 'source_message', 'for_user')},
        ),
        migrations.AlterUniqueTogether(
            name='spamreport',
            unique_together={('reporter', 'message', 'reason')},
        ),
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together={('jti',)},
        ),
        migrations.AddConstraint(
            model_name='jobqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='jobqueue_idempotency_unique'),
        ),
    ]
